{% extends "class.py" %}
{% block parentclass %}DefaultSite{% endblock %}
{% block class_doc %}
    {{ description if description else "Autogenerated Site Class." }}
{% endblock %}
{% block class_body %}
    NAME = "{{ name }}"
{% endblock %}